name: CI
on: [push]

jobs:

  build-with-pocketfft:
    runs-on: ubuntu-latest
    steps:
      - name: Check out deft
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install python dependencies
        run: python -m pip install --upgrade pip numpy
      - name: Configure and build deft with pocketfft
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Run tests
        run: |
          cd test
          python -m unittest

  build-with-fftw:
    runs-on: ubuntu-latest
    steps:
      - name: Check out deft
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create/activate conda environment and install fftw
        run: |
          conda create --name deft-fftw python=3 numpy cmake
          eval "$(conda shell.bash hook)" && conda activate deft-fftw
          conda install -c conda-forge fftw
      - name: Configure and build deft with fftw
        run: |
          eval "$(conda shell.bash hook)" && conda activate deft-fftw
          mkdir build
          cd build
          cmake -DDEFT_FFT_TYPE=FFTW \
                -DFFTW_INCLUDE_DIR=/usr/share/miniconda/envs/deft-fftw/include \
                -DFFTW_LIBRARY_DIR=/usr/share/miniconda/envs/deft-fftw/lib \
                ..
          make
      - name: Run tests
        run: |
          eval "$(conda shell.bash hook)" && conda activate deft-fftw
          cd test
          python -m unittest

  build-with-mkl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out deft
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create/activate conda environment and install mkl
        run: |
          conda create --name deft-mkl python=3 numpy cmake
          eval "$(conda shell.bash hook)" && conda activate deft-mkl
          conda install -c intel mkl-devel
      - name: Configure and build deft with mkl
        run: |
          eval "$(conda shell.bash hook)" && conda activate deft-mkl
          mkdir build
          cd build
          cmake -DDEFT_FFT_TYPE=MKL \
                -DMKL_INCLUDE_DIR=/usr/share/miniconda/envs/deft-mkl/include \
                -DMKL_LIBRARY_DIR=/usr/share/miniconda/envs/deft-mkl/lib \
                ..
          make
          export LD_LIBRARY_PATH=/usr/share/miniconda/envs/deft-mkl/lib:$LD_LIBRARY_PATH
      - name: Run tests
        run: |
          eval "$(conda shell.bash hook)" && conda activate deft-mkl
          cd test
          python -m unittest
